services:
  db:
    container-name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: stocks
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - StockPortfolioAnalysis
      